name: Nim Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: build
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
      - run: |
          nimble install -Y
          nimble install glm -Y
          nimble build_all
                